### ISSUE TITLE
can't build it

### ISSUE THREAD

**Issue by juliusmilan** [willkill07/adventofcode#2]
Hi Will, I would like to build and compare your advent of code 2015 solutions with mine regarding to performance, but I can't build it on debian 9 nor fedora 26

I get link error when I run ./compile.sh:
...
[ 93%] Building CXX object src/CMakeFiles/Advent.dir/Day24.cpp.o
[ 96%] Building CXX object src/CMakeFiles/Advent.dir/Day25.cpp.o
[100%] Linking CXX executable Advent
lib/libAdventUtils.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
src/CMakeFiles/Advent.dir/build.make:745: recipe for target 'src/Advent' failed
make[2]: *** [src/Advent] Error 1
CMakeFiles/Makefile2:87: recipe for target 'src/CMakeFiles/Advent.dir/all' failed
make[1]: *** [src/CMakeFiles/Advent.dir/all] Error 2
Makefile:127: recipe for target 'all' failed

Seems easy to solve, but I can't figure it out somehow.

**Comment by willkill07** [comment]
Fixed -- was an issue with libc++ having something marked as constexpr when libstdc++ didn't. I fixed the code (along with a few other things). Thanks for letting me know.
